apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapitest-deployment
spec:
  selector:
    matchLabels:
      app: restapitest-deployment
  template:
    metadata:
      labels:
        app: restapitest-deployment
    spec:
      containers:
      - name: restapi-db
        image: postgres:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: db-port
          containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres 
      - name: restapi-core-identity-server
        image: taraskrupko/restapi-core-identity-server-mydockerfile:1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: idserver-port
          containerPort: 8080
        envFrom:
          - configMapRef:
              name: rest-api-test-deploy-config
        # env:
        #   - name: IDENTITY_ISSUER
        #     value: http://localhost:8080
        #   - name: DatabaseConnection
        #     value: Host=localhost;Port=5432;Database=testdb;Username=postgres;Password=postgres
      - name: restapi-core-api
        image: taraskrupko/restapi-core-api-mydockerfile:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: api-port
          containerPort: 8081
        envFrom:
          - configMapRef:
              name: rest-api-test-deploy-config
        # env:
        #   - name: IdentityServer__Url
        #     value: http://localhost:8080
        #   - name: DatabaseConnection
        #     value: Host=localhost;Port=5432;Database=testdb;Username=postgres;Password=postgres
